# Generated by Django 3.2.19 on 2023-06-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.BigIntegerField(verbose_name='price (تومان)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_with_discount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='price_with_discount (تومان)'),
        ),
    ]
