# Generated by Django 4.2.2 on 2023-06-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='telegram_id'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='whatsapp_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='whatsapp_id'),
        ),
    ]
