# Generated by Django 4.2.2 on 2023-06-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_aboutus_phone_number_aboutus_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'AboutUs', 'verbose_name_plural': 'AboutUs'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='whatsapp_id',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='whatsapp_number'),
        ),
    ]
